- documents/rtb/interni/verbali/VI_2023_11_03.typ
> Aggiunto verbale interno 11-03-2023

- documents/candidatura/dichiarazione_impegni.typ
- documents/candidatura/lettera_di_presentazione.typ
- documents/candidatura/valutazione_capitolati.typ
- documents/candidatura/verbali/esterni/VE_2023_10_26-Zextras.typ
- documents/candidatura/verbali/interni/VI_2023_10_17.typ
- documents/candidatura/verbali/interni/VI_2023_10_19.typ
- documents/candidatura/verbali/interni/VI_2023_10_25.typ
- documents/rtb/interni/verbali/VI_2023_11_03.typ
- templates/common.typ
- templates/document.typ
Sistemati i problemi rilevati in fase di candidatura, tranne che per "versione nel nome del file" e "verbali approvati da committente", (tracciati da #16).
Closes #17.
> Fix candidatura, pt1

- documents/rtb/interni/norme_di_progetto.typ
> Definite struttura ed introduzione del documento Norme di Progetto

- documents/rtb/interni/norme_di_progetto.typ
Ho aggiunto nelle Norme di Progetto le sezioni 3.2 Verifica (#13) e 3.3 Validazione (#14).
Closes #13, closes #14
> aggiunta delle sezioni verifica e validazione

- .github/workflows/compile.yml
- README.md
- documents/rtb/interni/verbali/VI_2023_11_03.typ
- templates/common.typ
> Ci improvements

- documents/rtb/interni/norme_di_progetto.typ
> Stesura della sezione 'Documentazione'

- documents/rtb/esterni/verbali/VE_2023_11_09.typ
Closes #22
Il verbale verrà successivamente approvato e caricato in formato PDF nel branch `master`.
> Aggiunto verbale esterno del 2023-11-09

- documents/rtb/esterni/glossario.typ
> Definizione e aggiunta dei primi termini all'interno del glossario

- documents/candidatura/dichiarazione_impegni.typ
- documents/candidatura/lettera_di_presentazione.typ
- documents/candidatura/valutazione_capitolati.typ
- documents/candidatura/verbali/esterni/VE_2023_10_26-Zextras.typ
- documents/candidatura/verbali/interni/VI_2023_10_17.typ
- documents/candidatura/verbali/interni/VI_2023_10_19.typ
- documents/candidatura/verbali/interni/VI_2023_10_25.typ
- documents/diari/2023_10_30.typ
- documents/diari/2023_11_13.typ
- documents/rtb/esterni/analisi_requisiti.typ
- documents/rtb/esterni/glossario.typ
- documents/rtb/esterni/verbali/VE_2023_11_09.typ
- documents/rtb/interni/norme_di_progetto.typ
- documents/rtb/interni/verbali/VI_2023_11_03.typ
- templates/common.typ
- templates/document.typ
- templates/slides.typ
> Applicazione delle regole di stile definite nelle "Norme di Progetto" dove mancanti

- documents/rtb/interni/norme_di_progetto.typ
> Stesura della sezione 'Miglioramento'

- documents/rtb/esterni/piano_di_progetto.typ
> Piano di progetto: struttura e introduzione

- documents/rtb/esterni/piano_di_progetto.typ
- documents/rtb/esterni/piano_di_qualifica.typ
> Piano di qualifica: struttura e introduzione

- documents/rtb/interni/norme_di_progetto.typ
> Stesura della sezione 'Formazione'

- documents/rtb/esterni/piano_di_progetto.typ
- templates/document.typ
> Stesura della sezione 'Analisi dei Rischi'

- documents/rtb/interni/norme_di_progetto.typ
> Stesura della sezione 'Fornitura'

- documents/rtb/interni/norme_di_progetto.typ
> Stesura della sezione 'Sviluppo'

- documents/diari/2023_11_20.typ
> Aggiunto diario di bordo del 2023-11-20

- documents/rtb/interni/norme_di_progetto.typ
> Aggiornamento della sezione Comunicazioni

- documents/rtb/interni/norme_di_progetto.typ
> Stesura della sezione 'gestione della configurazione'

- documents/candidatura/valutazione_capitolati.typ
- documents/candidatura/verbali/esterni/VE_2023_10_26-Zextras.typ
- documents/candidatura/verbali/interni/VI_2023_10_17.typ
- documents/candidatura/verbali/interni/VI_2023_10_19.typ
- documents/candidatura/verbali/interni/VI_2023_10_25.typ
- documents/rtb/esterni/analisi_requisiti.typ
- documents/rtb/esterni/glossario.typ
- documents/rtb/esterni/verbali/VE_2023_11_09.typ
- documents/rtb/interni/norme_di_progetto.typ
- documents/rtb/interni/verbali/VI_2023_11_03.typ
> documents: add `;` and `.` to bulleted lists

- documents/rtb/interni/verbali/VI_2023_11_07.typ
> add: VI_2023_11_07

- documents/rtb/interni/norme_di_progetto.typ
> Stesure della sezione 'Gestione della qualità'

- documents/rtb/interni/verbali/VI_2023_11_09.typ
> add vi_2023_11_09

- documents/rtb/interni/verbali/VI_2023_11_22.typ
> add: VI_2023_11_22

- documents/rtb/interni/verbali/VI_2023_11_15.typ
> add VI_2023_11_15

- documents/rtb/esterni/piano_di_progetto.typ
> Stesura della sezione "Modello di sviluppo"

- documents/rtb/interni/norme_di_progetto.typ
> Norme di progetto: Standard per la qualitá

- documents/rtb/esterni/piano_di_progetto.typ
> Periodo I: stesura della pianificazione

- documents/diari/2023_11_29.typ
> Aggiunto diariodi bordo del 2023-11-29

- documents/rtb/esterni/analisi_dei_requisiti.typ
Prima versione del documento 2023-11-25
> Analisi dei Requisiti: prima versione del documento 2023-11-25

- documents/rtb/interni/verbali/VI_2023_11_28.typ
> add vi_2023_11_28

- documents/rtb/esterni/verbali/VE_2023_11_30.typ
> Stesura del verbale esterno del 2023-11-30

- documents/rtb/esterni/analisi_dei_requisiti.typ
> Casi d'uso: correzione login base e correzione scambio delle email

- documents/rtb/esterni/analisi_dei_requisiti.typ
> usecases: correzioni

- documents/rtb/esterni/analisi_dei_requisiti.typ
Casi d'uso: correzione degli stress test #110 
closes #110
> Casi d'uso: correzione degli stress test

- documents/rtb/esterni/analisi_dei_requisiti.typ
> Rimozione dei requisiti di vincolo e di prestazione

- documents/rtb/interni/verbali/VI_2023_11_30.typ
> add vi_2023_11_30

- documents/rtb/esterni/glossario.typ
> Inserimento termini principali

- documents/rtb/esterni/piano_di_progetto.typ
> Periodo II: stesura del preventivo

- documents/diari/2023_12_11.typ
> Creazione diario di bordo 2023_12_11

- documents/rtb/interni/verbali/VI_2023_12_08.typ
> Stesura del verbale interno del 2023-12-08

- documents/rtb/esterni/piano_di_progetto.typ
> Piano di Progetto: Consuntivo del periodo delle due settimane precedenti

- documents/rtb/interni/verbali/VI_2023_12_13.typ
> Stesura verbale 2023-12-13

- documents/rtb/esterni/piano_di_progetto.typ
> Piano di Progetto: Pianificazione e preventivo del periodo corrente

- documents/diari/2023_12_18.typ
> Creazione diario di bordo 2023_12_18

- documents/rtb/interni/norme_di_progetto.typ
> Norme di Progetto: Perfezionare la descrizione dei processi di supporto "Verifica" e "Validazione"

- documents/rtb/esterni/piano_di_qualifica.typ
- templates/document.typ
> Piano di Qualifica: Stesura delle sezioni Qualità di prodotto e Qualità di processo

- documents/rtb/esterni/glossario.typ
> Glossario: incremento del vocabolario

- documents/rtb/esterni/piano_di_qualifica.typ
- templates/document.typ
> Stesura della sezione 'Iniziative di automiglioramento per la qualità'

- documents/rtb/interni/verbali/VI_2023_12_21.typ
> Aggiunto VI-2023-12-21

- documents/rtb/esterni/verbali/VE_2023_12_18.typ
- templates/common.typ
> add VE_2023_12_18

- documents/rtb/esterni/analisi_dei_requisiti.typ
- documents/rtb/esterni/piano_di_qualifica.typ
- templates/document.typ
> Documents style

- documents/rtb/esterni/piano_di_progetto.typ
Closes #165 
Closes #166 
Closes #167
> Piano progetto

- documents/rtb/interni/verbali/VI_2024_01_03.typ
> add vi_2024_01_03

- documents/rtb/esterni/piano_di_progetto.typ
- documents/rtb/esterni/piano_di_qualifica.typ
- templates/document.typ
> add captions to images, graphs and tables

- documents/rtb/esterni/piano_di_qualifica.typ
> pdq: add testing methodologies

- documents/rtb/interni/norme_di_progetto.typ
> ndp: `jmap` repo description, branch and PRs

- documents/rtb/esterni/piano_di_progetto.typ
- templates/document.typ
> `pdp`: preventivo e pianificazione periodo 5
